# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2da70e8696a483e8fdf5cc6b384832863cf53e5af7559657d2d07c7b2affb63186383d76a3c1106e7f5c896fd5dd7f6c5da0ef8d236536870d122787570b4b97

test:
  secret_key_base: 6e77d3f4f1a09d6eec649fdc1620db68e7d60e732d94e49e47a4ed8ff2aea5abfb0e79c2dd47798b205a817e0b1f95b516ee05c72928520c8b11378773dcb136

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
