# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170126_2009'),
        ('belt', '0002_delete_bookmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='users',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='all_titles',
        ),
        migrations.AddField(
            model_name='reviews',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='belt.Books'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.Registrations'),
            preserve_default=False,
        ),
    ]
